version: '3.9'

services:
  ruuter:
    container_name: ovon_ruuter
    image: ruuter-ruuter
    environment:
      - application.cors.allowedOrigins=*
    volumes:
      - ./DSL:/DSL
    networks:
      - converter
    ports:
      - 8080:8080

  pipelines:
    container_name: ovon_pipelines
    build:
      context: ./Pipelines
    ports:
      - 3010:3010
    networks:
      - converter


networks:
  converter:
    driver: bridge